import { Mic, LayoutDashboard, FileText, CheckSquare, Lock, RefreshCw, Clock, Cloud } from 'lucide-react';
import './Features.css';

const coreFeatures = [
  { icon: <Mic size={17} />, title: 'Whisper Transcription', desc: 'Convert speech to text with industry-leading AI accuracy.' },
  { icon: <LayoutDashboard size={17} />, title: 'Collaborative Dashboard', desc: 'Manage team tasks and deadlines in one place.' },
  { icon: <FileText size={17} />, title: 'Smart Summaries', desc: 'Get concise meeting overviews generated by advanced LLMs.' },
  { icon: <CheckSquare size={17} />, title: 'Task Extraction', desc: 'Automatically identify action items and deadlines from audio.' },
  { icon: <Lock size={17} />, title: 'Secure Auth', desc: 'Protect sensitive meeting data with JWT encryption.' },
  { icon: <RefreshCw size={17} />, title: 'Real-time Updates', desc: 'Sync task statuses instantly across your entire team.' },
  { icon: <Clock size={17} />, title: 'History Tracking', desc: 'Review past meetings and track progress over time.' },
  { icon: <Cloud size={17} />, title: 'Cloud Storage', desc: 'Securely store and access your recordings anytime.' },
];

const advancedFeatures = [
  { icon: <CheckSquare size={16} />, title: 'AI Task Extraction', desc: 'Identify assignees and deadlines automatically from transcripts.' },
  { icon: <LayoutDashboard size={16} />, title: 'Interactive Task Boards', desc: 'Visual kanban boards that update in real time.' },
  { icon: <Lock size={16} />, title: 'Secure Data Vault', desc: 'Enterprise-grade security for all your meeting recordings.' },
  { icon: <FileText size={16} />, title: 'Deep Search Analytics', desc: 'Find specific keywords across all your meeting histories.' },
  { icon: <RefreshCw size={16} />, title: 'Custom API Integration', desc: 'Connect your meeting data with existing productivity tools.' },
];

export default function Features() {
  return (
    <section className="features" id="features">
      <div className="container">

        {/* Header */}
        <div className="features__header">
          <span className="badge"><span className="pulse-dot" />Core Services</span>
          <h2 className="section-title">Complete Meeting Intelligence</h2>
          <p className="section-sub">A comprehensive suite of tools designed to streamline your workflow — from automated transcription to real-time collaborative tracking.</p>
        </div>

        {/* Highlight 2-col */}
        <div className="features__hl-grid">
          <div className="features__hl-card features__hl-card--blue">
            <div className="features__hl-icon"><Mic size={20} /></div>
            <h3>Whisper Transcription</h3>
            <p>Experience seamless audio-to-text conversion using the Whisper API, ensuring every detail of your discussion is captured perfectly for future reference and analysis.</p>
          </div>
          <div className="features__hl-card features__hl-card--indigo">
            <div className="features__hl-icon"><LayoutDashboard size={20} /></div>
            <h3>Collaborative Dashboard</h3>
            <p>Monitor team performance, track task completion, and ensure that no critical action item ever falls through the cracks again with our intelligent dashboard.</p>
          </div>
        </div>

        {/* Core grid */}
        <div className="features__grid">
          {coreFeatures.map((f, i) => (
            <div key={i} className="features__card">
              <div className="features__card-icon">{f.icon}</div>
              <h4>{f.title}</h4>
              <p>{f.desc}</p>
            </div>
          ))}
        </div>

        {/* Smart Automation */}
        <div className="features__automation">
          <div className="features__auto-left">
            <span className="badge"><span className="pulse-dot" />Smart Automation</span>
            <h2 className="section-title">Revolutionize How Your Team Handles Meetings</h2>
            <p className="section-sub">Experience AI-driven organization that turns every meeting into a roadmap for success.</p>
            <div className="features__auto-tag">
              <div className="features__auto-dot" />
              <div>
                <div className="features__auto-tag-title">Automated Task Management System</div>
                <div className="features__auto-tag-sub">AI Powered Workflow Efficiency — Turn conversations into organized project boards.</div>
              </div>
            </div>
          </div>
          <div className="features__auto-right">
            <div className="features__adv-header">
              <span className="badge"><span className="pulse-dot" />Advanced Features</span>
            </div>
            <div className="features__adv-list">
              {advancedFeatures.map((f, i) => (
                <div key={i} className="features__adv-item">
                  <div className="features__adv-icon">{f.icon}</div>
                  <div>
                    <div className="features__adv-title">{f.title}</div>
                    <div className="features__adv-desc">{f.desc}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Research Driven */}
        <div className="features__research">
          <div className="features__research-cards">
            <div className="features__research-card">
              <div className="features__research-icon"><FileText size={18} /></div>
              <h4>Intelligent Transcript Analysis Engine</h4>
              <p>Our LLM-driven engine parses complex discussions to find the underlying intent and critical business requirements instantly.</p>
            </div>
            <div className="features__research-card">
              <div className="features__research-icon"><FileText size={18} /></div>
              <h4>Semantic Search Capabilities</h4>
              <p>Navigate through hours of recordings in seconds by searching for concepts rather than just exact words.</p>
            </div>
          </div>
          <div className="features__research-right">
            <span className="badge"><span className="pulse-dot" />Research Driven</span>
            <h2 className="section-title">Actionable Insights From Audio</h2>
            <p className="section-sub">Unlock the hidden potential within your team's conversations by leveraging cutting-edge AI to organize, analyze, and execute on every great idea shared.</p>
          </div>
        </div>

        {/* Team Collaboration */}
        <div className="features__collab">
          <div className="features__collab-inner">
            <span className="badge"><span className="pulse-dot" />Team Collaboration</span>
            <h2 className="section-title">Centralized Task Management</h2>
            <p className="section-sub">Our collaborative task board lets teams update statuses, set priorities, and track completion rates in a beautiful, responsive interface built for speed.</p>
          </div>
          <div className="features__board">
            <div className="features__board-col">
              <div className="features__board-col-title">To Do</div>
              {['Write API docs', 'Review PR #42'].map(t => (
                <div key={t} className="features__board-item">{t}</div>
              ))}
            </div>
            <div className="features__board-col">
              <div className="features__board-col-title features__board-col-title--blue">In Progress</div>
              {['Design System', 'Backend Auth'].map(t => (
                <div key={t} className="features__board-item">{t}</div>
              ))}
            </div>
            <div className="features__board-col">
              <div className="features__board-col-title features__board-col-title--green">Done</div>
              {['DB Schema', 'Onboarding'].map(t => (
                <div key={t} className="features__board-item features__board-item--done">{t}</div>
              ))}
            </div>
          </div>
        </div>

      </div>
    </section>
  );
}
