import { Mic, LayoutDashboard, FileText, CheckSquare, Lock, RefreshCw, Clock, Cloud } from 'lucide-react';
import './Features.css';

const coreFeatures = [
  {
    icon: <Mic size={20} />,
    title: 'Whisper Transcription',
    desc: 'Convert speech to text with industry-leading AI accuracy.',
  },
  {
    icon: <LayoutDashboard size={20} />,
    title: 'Collaborative Dashboard',
    desc: 'Manage team tasks and deadlines in one place.',
  },
  {
    icon: <FileText size={20} />,
    title: 'Smart Summaries',
    desc: 'Get concise meeting overviews generated by advanced LLMs.',
  },
  {
    icon: <CheckSquare size={20} />,
    title: 'Task Extraction',
    desc: 'Automatically identify action items and deadlines from audio.',
  },
  {
    icon: <Lock size={20} />,
    title: 'Secure Auth',
    desc: 'Protect your sensitive meeting data with JWT encryption.',
  },
  {
    icon: <RefreshCw size={20} />,
    title: 'Real-time Updates',
    desc: 'Sync task statuses instantly across your entire team.',
  },
  {
    icon: <Clock size={20} />,
    title: 'History Tracking',
    desc: 'Review past meetings and track progress over time.',
  },
  {
    icon: <Cloud size={20} />,
    title: 'Cloud Storage',
    desc: 'Securely store and access your recordings anytime, anywhere.',
  },
];

const advancedFeatures = [
  {
    icon: <CheckSquare size={18} />,
    title: 'AI Task Extraction',
    desc: 'Identify assignees and deadlines automatically from transcripts.',
  },
  {
    icon: <LayoutDashboard size={18} />,
    title: 'Interactive Task Boards',
    desc: 'Identify assignees and deadlines automatically from transcripts.',
  },
  {
    icon: <Lock size={18} />,
    title: 'Secure Data Vault',
    desc: 'Enterprise-grade security for all your meeting recordings.',
  },
  {
    icon: <FileText size={18} />,
    title: 'Deep Search Analytics',
    desc: 'Find specific keywords across all your meeting histories.',
  },
  {
    icon: <RefreshCw size={18} />,
    title: 'Custom API Integration',
    desc: 'Connect your meeting data with existing productivity tools.',
  },
];

export default function Features() {
  return (
    <section className="features" id="features">
      <div className="container">
        {/* Core Services */}
        <div className="features__intro">
          <span className="section-badge"><span className="glow-dot" />Our Core Services</span>
          <h2 className="section-title">Complete Meeting Intelligence Solutions</h2>
          <p className="section-sub">
            MeetFlow AI provides a comprehensive suite of tools designed to streamline your workflow, from automated transcription and intelligent task assignment to secure data management and real-time collaborative tracking for modern professional teams.
          </p>
        </div>

        <div className="features__highlight">
          <div className="features__highlight-card features__highlight-card--blue">
            <div className="features__hl-icon"><Mic size={22} /></div>
            <h3>Whisper Transcription</h3>
            <p>Experience seamless audio-to-text conversion using the Whisper API, ensuring every detail of your discussion is captured perfectly for future reference and analysis.</p>
          </div>
          <div className="features__highlight-card features__highlight-card--purple">
            <div className="features__hl-icon"><LayoutDashboard size={22} /></div>
            <h3>Collaborative Dashboard</h3>
            <p>Leverage our intelligent dashboard to monitor team performance, track task completion, and ensure that no critical action item ever falls through the cracks again.</p>
          </div>
        </div>

        <div className="features__grid">
          {coreFeatures.map((f, i) => (
            <div key={i} className="features__card">
              <div className="features__card-icon">{f.icon}</div>
              <h4>{f.title}</h4>
              <p>{f.desc}</p>
            </div>
          ))}
        </div>

        {/* Smart Automation */}
        <div className="features__automation">
          <div className="features__auto-left">
            <span className="section-badge"><span className="glow-dot" />Smart Automation</span>
            <h2 className="section-title">Revolutionize How Your Team Handles Meetings</h2>
            <p className="section-sub">Experience the power of AI-driven organization that turns every meeting into a roadmap for success.</p>

            <div className="features__auto-tag">
              <div className="features__auto-tag-dot" />
              <div>
                <div className="features__auto-tag-title">Automated Task Management System</div>
                <div className="features__auto-tag-sub">AI Powered Workflow Efficiency — Turn conversations into organized project boards.</div>
              </div>
            </div>
          </div>

          <div className="features__auto-right">
            <div className="features__auto-card-header">
              <span className="section-badge" style={{marginBottom: 0}}><span className="glow-dot"/>Advanced Features for High Performing Remote Teams</span>
            </div>
            <div className="features__adv-list">
              {advancedFeatures.map((f, i) => (
                <div key={i} className="features__adv-item">
                  <div className="features__adv-icon">{f.icon}</div>
                  <div>
                    <div className="features__adv-title">{f.title}</div>
                    <div className="features__adv-desc">{f.desc}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Research Driven */}
        <div className="features__research">
          <div className="features__research-right">
            <span className="section-badge"><span className="glow-dot"/>Research Driven</span>
            <h2 className="section-title">Actionable Insights From Audio</h2>
            <p className="section-sub">
              Unlock the hidden potential within your team's conversations by leveraging cutting-edge artificial intelligence to organize, analyze, and execute on every single great idea shared.
            </p>
          </div>
          <div className="features__research-cards">
            <div className="features__research-card">
              <div className="features__research-icon"><FileText size={20} /></div>
              <h4>Intelligent Transcript Analysis Engine</h4>
              <p>Our LLM-driven engine parses complex discussions to find the underlying intent and critical business requirements instantly.</p>
            </div>
            <div className="features__research-card">
              <div className="features__research-icon"><FileText size={20} /></div>
              <h4>Semantic Search Capabilities</h4>
              <p>Navigate through hours of recordings in seconds by searching for concepts rather than just exact words.</p>
            </div>
          </div>
        </div>

        {/* Team Collaboration */}
        <div className="features__collab">
          <div className="features__collab-inner">
            <span className="section-badge"><span className="glow-dot"/>Team Collaboration</span>
            <h2 className="section-title">Centralized Task Management and Tracking</h2>
            <p className="section-sub">Our collaborative task board allows teams to update statuses, set priorities, and track completion rates in a beautiful, responsive interface built for speed.</p>
          </div>
          <div className="features__collab-board">
            <div className="features__board-col">
              <div className="features__board-col-title">To Do</div>
              {['Write API docs', 'Review PR #42'].map(t => (
                <div key={t} className="features__board-item">{t}</div>
              ))}
            </div>
            <div className="features__board-col">
              <div className="features__board-col-title features__board-col-title--blue">In Progress</div>
              {['Design System Update', 'Backend Auth'].map(t => (
                <div key={t} className="features__board-item">{t}</div>
              ))}
            </div>
            <div className="features__board-col">
              <div className="features__board-col-title features__board-col-title--green">Done</div>
              {['DB Schema', 'Onboarding Flow'].map(t => (
                <div key={t} className="features__board-item features__board-item--done">{t}</div>
              ))}
            </div>
          </div>
        </div>

      </div>
    </section>
  );
}
