import { Check, Zap } from 'lucide-react';
import './Pricing.css';

const plans = [
  {
    name: 'Starter',
    price: '0',
    period: 'month',
    desc: 'Perfect for individuals and small teams getting started.',
    features: [
      '5 meeting recordings/mo',
      'Basic AI transcription',
      'Smart summaries',
      '1 GB cloud storage',
      'Email support',
    ],
    cta: 'Get Started Free',
    highlight: false,
  },
  {
    name: 'Pro',
    price: '29',
    period: 'month',
    desc: 'Ideal for growing teams that need more power and collaboration.',
    features: [
      'Unlimited recordings',
      'Advanced Whisper AI transcription',
      'Automated task extraction',
      'Collaborative dashboard',
      '50 GB cloud storage',
      'Real-time sync',
      'Priority support',
    ],
    cta: 'Start Pro Trial',
    highlight: true,
    badge: 'Most Popular',
  },
  {
    name: 'Enterprise',
    price: '99',
    period: 'month',
    desc: 'For large organizations with advanced security and integrations.',
    features: [
      'Everything in Pro',
      'SSO & JWT auth',
      'Custom API integrations',
      'Unlimited cloud storage',
      'Deep search analytics',
      'Dedicated account manager',
      'SLA guarantee',
    ],
    cta: 'Contact Sales',
    highlight: false,
  },
];

const faqs = [
  {
    q: 'How accurate is the AI transcription for different accents and technical terms?',
    a: 'Our system uses the Whisper API, which is trained on diverse datasets to ensure high accuracy across various accents and specialized industry terminology for professional-grade transcripts every single time.',
  },
  {
    q: 'Can I edit the tasks after they are automatically generated by AI?',
    a: 'Yes, the collaborative task board allows full CRUD functionality, meaning you can edit titles, change assignees, adjust deadlines, or delete tasks to ensure your project board remains perfectly accurate.',
  },
  {
    q: 'What file formats are supported for meeting recording uploads?',
    a: 'We support all major audio and video formats, including MP3, WAV, and MP4, allowing you to upload recordings from any conferencing tool or mobile device with total ease.',
  },
  {
    q: 'Is my meeting data secure and private on your platform?',
    a: 'Absolutely, we utilize JWT authentication and secure MongoDB storage to ensure that only authorized users can access your recordings and transcripts, maintaining the highest standards of data privacy.',
  },
];

export default function Pricing() {
  return (
    <section className="pricing" id="pricing">
      <div className="container">

        {/* Value First Banner */}
        <div className="pricing__value">
          <span className="section-badge"><span className="glow-dot"/>Value First</span>
          <h2 className="section-title">The Ultimate Platform for Turning Meetings Into Productive Team Results</h2>
          <p className="section-sub">We bridge the gap between verbal communication and project execution through seamless AI-driven automation and organization.</p>
        </div>

        {/* Plans */}
        <div className="pricing__plans">
          {plans.map((plan, i) => (
            <div key={i} className={`pricing__plan ${plan.highlight ? 'pricing__plan--highlight' : ''}`}>
              {plan.badge && (
                <div className="pricing__badge">{plan.badge}</div>
              )}
              <div className="pricing__plan-name">{plan.name}</div>
              <div className="pricing__plan-price">
                <span className="pricing__dollar">$</span>
                <span className="pricing__amount">{plan.price}</span>
                <span className="pricing__period">/{plan.period}</span>
              </div>
              <p className="pricing__plan-desc">{plan.desc}</p>
              <ul className="pricing__features">
                {plan.features.map((f, j) => (
                  <li key={j}>
                    <Check size={14} className="pricing__check" />
                    {f}
                  </li>
                ))}
              </ul>
              <a
                href="#contact"
                className={plan.highlight ? 'btn-primary pricing__cta' : 'btn-outline pricing__cta'}
              >
                {plan.cta}
              </a>
            </div>
          ))}
        </div>

        {/* Testimonials */}
        <div className="testimonials" id="testimonial">
          <div className="testimonials__intro">
            <span className="section-badge"><span className="glow-dot"/>User Stories</span>
            <h2 className="section-title">Trusted by Industry Leaders</h2>
            <p className="section-sub">Discover how professionals are using MeetFlow AI to reclaim their time and boost team productivity.</p>
          </div>
          <div className="testimonials__grid">
            {[
              { name: 'Akhila Uggina', role: 'Project Lead', text: 'MeetFlow AI has completely transformed our project management workflow. We no longer waste time manually taking notes; the AI captures every task perfectly. It has allowed our team to focus on the actual work rather than administrative overhead.', init: 'AU' },
              { name: 'James Wilson', role: 'Product Designer', text: 'I love the clean interface and how easy it is to navigate between the transcript and the task board. The security features give me peace of mind knowing our proprietary discussions are kept safe and private at all times.', init: 'JW' },
              { name: 'Sarah Chen', role: 'Operations Manager', text: 'The automated task extraction is a game-changer for our weekly sprints. It identifies deadlines I might have missed and assigns them to the right people instantly. Our meeting productivity has increased by at least fifty percent.', init: 'SC' },
              { name: 'Elena Rodriguez', role: 'Tech Lead', text: 'The integration between the transcript and the task board is seamless. It\'s the first tool I\'ve used that actually understands the context of our technical discussions and has saved us hours of manual entry.', init: 'ER' },
              { name: 'Michelle Taylor', role: 'Marketing Head', text: 'The ROI on this tool was immediate. By automating the follow-up process, our team stays aligned and accountable without any extra effort. It\'s professional, fast, and incredibly intuitive to use.', init: 'MT' },
              { name: 'David Park', role: 'Creative Director', text: 'MeetFlow AI is the missing link in our remote work toolkit. The summary feature is particularly helpful for catching up on meetings I couldn\'t attend personally, providing all the key takeaways instantly.', init: 'DP' },
            ].map((t, i) => (
              <div key={i} className="testimonial__card">
                <div className="testimonial__stars">{'★★★★★'}</div>
                <p className="testimonial__text">"{t.text}"</p>
                <div className="testimonial__author">
                  <div className="testimonial__avatar">{t.init}</div>
                  <div>
                    <div className="testimonial__name">{t.name}</div>
                    <div className="testimonial__role">{t.role}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* FAQ */}
        <div className="faq">
          <div className="faq__intro">
            <span className="section-badge"><span className="glow-dot"/>Frequently Asked Questions</span>
          </div>
          <div className="faq__list">
            {faqs.map((f, i) => (
              <details key={i} className="faq__item">
                <summary className="faq__q">{f.q}</summary>
                <p className="faq__a">{f.a}</p>
              </details>
            ))}
          </div>
        </div>

        {/* CTA Banner */}
        <div className="cta-banner" id="contact">
          <div className="cta-banner__orb" />
          <span className="section-badge"><span className="glow-dot"/>Get Started</span>
          <h2 className="section-title">Ready to Optimize Your Meetings?</h2>
          <p className="section-sub" style={{margin:'0 auto 32px'}}>Join thousands of teams turning their conversations into structured, actionable project plans.</p>
          <a href="#" className="btn-primary cta-banner__btn">
            <Zap size={16} /> Start For Free
          </a>
        </div>

      </div>
    </section>
  );
}
